Repository washingtonpost/elex-live-model, pull requests merged in 2022-10, with the labels that each got.

#14 Fix release workflow
  .github/workflows/release.yml
  README.md
  setup.py
Labels: :thought_balloon: wip

#15 Add data README
  README-data.md
  README.md
Labels: :bell: ready for review

#16 Release/v1.0.6
  .github/workflows/release.yml
  CHANGELOG.md
  README-data.md
  README.md
  setup.py
  src/elexmodel/client.py
  src/elexmodel/distributions/GaussianModel.py
  src/elexmodel/handlers/data/CombinedData.py
  src/elexmodel/models/BaseElectionModel.py
  src/elexmodel/models/GaussianElectionModel.py
  src/elexmodel/utils/math_utils.py
  tests/integration_test.sh
  tests/models/test_base_election_model.py
  tests/utils/test_math_utils.py
Labels: :bell: ready for review, :package: release

#18 elex-1507 fix mape when uncontested historical baseline
  src/elexmodel/utils/math_utils.py
  tests/utils/test_math_utils.py
Labels: :bell: ready for review

#19 Elex 1509 ecos solver fix when relative weights small
  src/elexmodel/models/BaseElectionModel.py
Labels: :bell: ready for review
